# ========== MONGODB ==========
spring.data.mongodb.uri=mongodb://localhost:27017/interview_copilot
spring.data.mongodb.auto-index-creation=true

# ========== JWT ==========
jwt.secret=interview-copilot-super-secret-dev-key-minimum-32-characters-safe123
jwt.expiration=86400000

# ========== FILE UPLOAD ==========
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ========== LOGGING ==========
logging.level.root=INFO
logging.level.com.interviewcopilot=DEBUG

# ========== SWAGGER ==========
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


gemini.api.key=AIzaSyBlWGwuUCxKvm3nAsosJzC6mAgoOkEuBRg
gemini.model=gemini-1.5-flash